language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
    - '.hoarder-cache'

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "3oqab4pCYlu3AUW5LXyeH+8RJiGkUSMFbFXMqZBV9/HK7xAW0rO/cDu/AU6haTovGKoEWTdVc43inVnnNm+FaCiIOqYhZPdwSIUQgGaqobdKP2VZgMBCnw8tRyryo/0LERue5ZipGkYclr3u/iM8I9psVb5nnXgyJWcMauJh1eTalvZFdp8mADwWr78FwisQWO3JhjJ5QzWP5beVZgZ8TWntR2PON5XfKNSfqgIoWqloV+6kkXXafm5R14bIR7NGNiXs0Dsh8xP4QZXO8voaP5oOU1XIbSlj6NEv4lFVoNxEc7+BtnhWiMbGt8xjPHhkLdqx2Kh0lahGw5UkDmuGSvqzyPZgJYfiYE2YsolohTn2OpfxFjxI2FUrjs6iD0+j4W5JfUGzesTT3l1PncJeowsLI3hkm9eD61WvEJDlyUPXgKPLM2bpy1PzPii8KKYEkjqiEY+IEBBNIjjDT1txYzowGwDzQCtJCVZXZNiMQP6P3G7GS//1G8vPe57rc0eu4kg71hZaMnElBSLcTTa/d5Fibrt3F06rf+fTG+ssJkTLWW7paR6qIY414YsAJxaBfwiiY0sKq9TmaEn4GujhXOCbi+vQKU+hFj3iou7phM8CmjoLjcNy37SqyrEDxZDYgHF3tyN2xW73cRVwELsiGGX6Xnj7ZcwdpJFohuc0tLM="
    # GITHUB_TOKEN
    - secure: "Z2JZJK5lnHBYNQj31Fd2BA3TPId4cdkFgEZolQtchmtgDYs+HzU2I4Uix/9jWA1tbdRvonoXfltoKUklxUb+aKZ8g5obI+6eHEcZ/fFM+qFnBAVmbTT0iNM5M61FkyB0perGxwM+itkZBWZnoZPugXMFTDFBOycZryTZjtooaEgnhNvRUvnZqW48U1VfcGsiQeF/ZclO/AlLaDBOUdzDg/3Bb9KTO2NGlOh6/t1Tmj4z70Sduz1HZJEypQov6HGZDjLFusjUu0XueCSWWueMOv0kauh0xIicSP128+nZARqjdjHubv5xjm4HhodvajGvPOn7qR05/TGve/ObWxFvzQ77aOn4J6PiYdactqHeQwGfrULcYwlUQvzi4mTE28My10+IM2jxabpv7MSchysVt56WF7xL1y8+jRLuGFCN6UckJtRqqTcVwYZxnWTASAECyQJ3G9YsTp7PJX7ocMcS4bogyz8ylqtW/zTbOFREdDJ3VMM/amHL02GLKLUR6hhLs8GeI0xnr/GqHfRPGIn/kvva/LuVLu2FXgV2vZ2XRYvNHNvIR78UZVn87+Atw5QkEPYfohowh5iklHzpZ28RyYwZntt7aNh9nkvabGiOo/b5/rmAvGSkc6VFvhPXeCVUL0hmmB39ZnzrBF24utqQssiQWNIK6itFhjqQGnvfbCQ="
    # GITHUB_ACCESS_TOKEN
    - secure: "lX7rM+lAO4zvitUbk9BY9bVud5+3ba5unCbgDP0NAqLVMmsVg3YeeYC5Ue8jsTA83O+/n9VIqxAdb21hsuNLNy2ogscJ9GfEBHXl8jf9MyGaCb/kLhYsoiFDiJcLmPS94G31K8wsbqAJpfCVpaXQbb26nAlRYtxPbTHUCfyn3Gegx7X+bVr3b2nHDZlyTqRRlr8ELZ7Uycd4FCA6LiHRyJrx4hMSV/c1zNI/Fff2NGEAFZIZsmgEM90wM39P6O7yz4QXXQ5V+gI7cIYkvoqgm6jNFR5ZuzBn4iVV5UTUChSwf2ptQpVUkB9x/A1/6gImNs4HCIP9Wn/YjJBeqtPt0llmP9pQ/gkJpNmgePkd5rJ0+IPrx/pkx0kTO5dD2EK7WRcZBGTqESLdPIwJ+X1frsLeMx1n/6GdlabfpqvcdoX84doh+y/fz/iH39WaN35/wN/1hZ71oJt44wIU1e1cxX12bLTSDZP9BgyfhHurpuNTsAyopAf6gCJLdZZNPgro7njZuNfho9kvq2gLtfQFlBCS3WowWCFBWS/qvzO+V8XC6aAT2ti86B+jfNy0fILYOCC2SUTcYThVooYEp35RVJnToc9JrKcxvRfpFpmmVQq4MrKq14g6HHTavyP0kZ/xs+E7nfUoGPCYOLTkPxC4e4EHxfaL6ZaXd/G8kKTxLko="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "tbFxh0tH7iwPDWcPa/sDcnR2aQB/zNDZc+BPYVunqZzk4uTlYhkvVA8K9ELk6gSh5RHtoijs+PSe40T467zXO19vpFgLpSnLOvbHsFrwcWMbAoOnjruqC7qTONM1QusNqrRXyDYdkUKqRU0g8Sfu2ERvjaRI/AsET2+HT02vxhiT72aL8sN0l3y+/7GZNxMzwtYRpnQIkzyHyYgDrjWY4keXFDiNBPXosCb+wm9oQVGufwaF1I2FWSBK4Vx+QHRzi9/cY1CaeqcKxnjDV7rgHoHDn3yL1czbBwHICVi7FTi71DK5jzU7/o0D48a2ShulnWz9RQPCxv5Qx3nu/6tEtaBguiclr7/mT/EZW/0w2JF17cYs7UgK1emOkBi98Q7NZNxqZ9gh8EpEaPy5ZygfQeDmqoBFEj/7xB2/dkm0/+lUunQ8KkRhCk5OI1IeUwFkam+7IYLPn++64XlRYhhT+HGbMinQIuS2dtcGYtCzBriWnK3/2mSrKUw0Fh1Z5I92F5OEEjQZab85SRgYYmSuZe1WKbkUWLNBldXOpzFX3xN+lKMCFkRVOyQHeZhvRUC4GDwExwdSrLDkUr85EfP/1zszV7k/3CmV45+wyhXe/VMLn6DH0EznQ0YJVUTJAtKxR6oUF3lBT/XUjldOSt+19AWxFs0qWvzXeNuO7HYMVzk="

install:
  - $SBT transferCommonResources
  - scripts/commonSetup

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script: scripts/tectonicPublishAndTag

      git:
        depth: false

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
